name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies from requirements.txt
      run: pip install -r requirements.txt

    - name: Upload installed environment
      uses: actions/upload-artifact@v4
      with:
        name: python-env
        path: .

  run_chrome_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies from requirements.txt
      run: pip install -r requirements.txt

    - name: Run headless Chrome tests
      run: |
        robot -d logs/chrome -v BASE_URL:${{ secrets.BASE_URL }} -v BROWSER:headlesschrome tests

    - name: Upload Chrome logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: chrome
        path: logs/chrome/
  
  run_firefox_tests:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies from requirements.txt
      run: pip install -r requirements.txt

    - name: Run headless Firefox tests
      run: |
        robot -d logs/firefox -v BASE_URL:${{ secrets.BASE_URL }} -v BROWSER:headlessfirefox tests

    - name: Upload Firefox logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: firefox
        path: logs/firefox/

  run_safari_tests:
    needs: install_dependencies
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Enable safaridriver
      run: sudo safaridriver --enable

    - name: Install dependencies from requirements.txt
      run: pip install -r requirements.txt

    - name: Run Safari tests
      run: |
        robot -d logs/safari -v BASE_URL:${{ secrets.BASE_URL }} -v BROWSER:safari tests

    - name: Upload Safari logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: safari
        path: logs/safari/

  publish_report:
    needs: [run_chrome_tests, run_firefox_tests, run_safari_tests]
    runs-on: ubuntu-latest

    steps:
    - name: Download Chrome logs
      uses: actions/download-artifact@v4
      with:
        name: chrome
        path: logs/headlesschrome/

    - name: Download Firefox logs
      uses: actions/download-artifact@v4
      with:
        name: firefox
        path: logs/headlessfirefox/

    - name: Download Safari logs
      uses: actions/download-artifact@v4
      with:
        name: safari
        path: logs/safari/

    - name: Publish test results as a GitHub Pages site
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GH_PAGES_TOKEN }}
        external_repository: ${{ github.repository }}
        publish_dir: ./logs/
        publish_branch: gh-pages
        commit_message: "Publish Bah.Ai Report"